//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HealthSearch
{
    using System;
    using System.Collections.Generic;
    
    public partial class PrestadorServico
    {
        public int idPrestador { get; set; }
        public int idServico { get; set; }
        public Nullable<System.DateTime> eliminado { get; set; }
    
        public virtual Prestador Prestador { get; set; }
        public virtual Servico Servico { get; set; }
    }
}
