//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HealthSearch
{
    using System;
    using System.Collections.Generic;
    
    public partial class VwPrestadorLocalizacao
    {
        public int id { get; set; }
        public int idLocalizacao { get; set; }
        public string nome { get; set; }
        public string morada { get; set; }
        public string telefone { get; set; }
        public string email { get; set; }
        public Nullable<System.DateTime> eliminado { get; set; }
        public string pais { get; set; }
        public string regiao { get; set; }
        public string distrito { get; set; }
        public string concelho { get; set; }
    }
}
